services:
  influxdb:
    image: influxdb:1.8
    platform: linux/amd64
    container_name: locust-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=locust
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: locust-grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning
      - ./deploy/grafana/provisioning/dashboards/locust_dashboard.json:/var/lib/grafana/dashboards/locust_dashboard.json

  chronograf:
    image: chronograf:latest
    container_name: locust-chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb
    links:
      - influxdb

  locust-master:
    build: .
    image: my-locust-image:latest
    container_name: locust-master
    ports:
      - "8089:8089"
      - "5557:5557"
    environment:
      - LOCUST_MODE=master
      - PROJECT=crm
      - ENV=dev
      - INFLUXDB_HOST=influxdb
    volumes:
      - ./:/mnt/locust
    command: -f locustfile.py --master
    links:
      - influxdb
    depends_on:
      - influxdb

  locust-worker:
    build: .
    image: my-locust-image:latest
    container_name: locust-worker
    environment:
      - LOCUST_MODE=worker
      - LOCUST_MASTER_NODE_HOST=locust-master
      - LOCUST_MASTER_PORT=5557
      - PROJECT=crm
      - ENV=dev
      - INFLUXDB_HOST=influxdb
    volumes:
      - ./:/mnt/locust
    command: -f locustfile.py --worker
    links:
      - locust-master
      - influxdb
    depends_on:
      - locust-master
      - influxdb

volumes:
  influxdb-data:
  grafana-data:
